//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaughtItHere
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishType
    {
        public FishType()
        {
            this.Fish = new HashSet<Fish>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Name { get; set; }
    
        public virtual ICollection<Fish> Fish { get; set; }
    }
}
