USE [master]
GO

/****** Object:  Database [CaughtItHere]    Script Date: 8/5/2014 9:56:29 AM ******/
CREATE DATABASE [CaughtItHere]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CaughtItHere', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CaughtItHere.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CaughtItHere_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CaughtItHere_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CaughtItHere] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CaughtItHere].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CaughtItHere] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CaughtItHere] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CaughtItHere] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CaughtItHere] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CaughtItHere] SET ARITHABORT OFF 
GO

ALTER DATABASE [CaughtItHere] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CaughtItHere] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CaughtItHere] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CaughtItHere] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CaughtItHere] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CaughtItHere] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CaughtItHere] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CaughtItHere] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CaughtItHere] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CaughtItHere] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CaughtItHere] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CaughtItHere] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CaughtItHere] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CaughtItHere] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CaughtItHere] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CaughtItHere] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CaughtItHere] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CaughtItHere] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CaughtItHere] SET  MULTI_USER 
GO

ALTER DATABASE [CaughtItHere] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CaughtItHere] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CaughtItHere] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CaughtItHere] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CaughtItHere] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CaughtItHere] SET  READ_WRITE 
GO

